### ISSUE TITLE
[Anon] Bug report: Dwarven Holds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#18]
**File:** Dwarven Holds.catz

**BattleScribe version:** 1.15.07

**Platform:** Linux

**Dropbox:** No

**Description:** Details:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.
> Dwarven Holds v2: The catalogue data file is invalid:
> net.battlescribe.model.catalogue.Profile@d584f60: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@6e1fd915: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@637d425e: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@777387a6: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@4c709031: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@6d5a911c: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@1a4340c0: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@45d1d320: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@3d93bdb5: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@5e782077: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@986fff7: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@2b5c6650: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@7433a719: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@5be88c45: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@518b3cb7: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@129425fe: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@662f4d8a: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@ed7e3b3: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@3a469b35: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@297b2052: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@5b6a0720: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@6cf25a2b: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@6f04499: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@2545a73b: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@67ffc6f5: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@6b4a77a7: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@73f66fa5: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@53c1a5aa: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@4e6366db: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@402e5bfe: Characteristic must match a characteristic from the profile type
> net.battlescribe.model.catalogue.Profile@711cd79d: Characteristic must match a characteristic from the profile type
	at net.battlescribe.desktop.rostereditor.g.f(BattleScribe:232)
	at net.battlescribe.desktop.rostereditor.g.b(BattleScribe:510)
	at net.battlescribe.desktop.rostereditor.g.b(BattleScribe:45)
	at net.battlescribe.desktop.rostereditor.g$2.actionPerformed(BattleScribe:350)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at java.awt.Component.show(Component.java:1655)
	at java.awt.Component.setVisible(Component.java:1607)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.f(BattleScribe:2886)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.i(BattleScribe:85)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame$11.actionPerformed(BattleScribe:2164)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by Toreador13** [comment]
Make sure you have the latest version of the Fantasy Battles The 9th Age.gstz  I can open the current files from the repository with no issue. the Game System File would be the only thing that would cause this issue, and we did have some changes from the original. Try that. No one else that I know of is having the issue, so I don't think it would be linux specific.
